### PR TITLE
updates to ecahm2020 notebook

### PR DESCRIPTION
**Pull request by jhamman**

### CODE REVIEW

**Comment by jhamman** [comment]
Thanks @jukent for all your work on this so far. I will take on the pointwise downscaler section, here's a punch list of things to do before tomorrow afternoon:

- move as many references as possible to the end of the notebook. I started a references section there but could use help pulling refs into it. 
- cleanup zscore plotting a bit. I'm leaning toward putting these plotting sections in `utils.py` just to clean up the notebook a bit. Plotting in python is not the point of this notebook. 
- review my changes from today, and help smooth the transition into the zscore section. I choose to make this section a bit of demo for how to build your own downscaling method. Thoughts?

**Comment by jukent** [comment]
@jhamman do you mean the skdownscale/pointwise_models/utils.py file? I will start moving code there. I agree the plotting is too bulky.

Thanks for expanding more upon the actual ZScoreRegressor class, that was definitely needed.

**Comment by jukent** [comment]
Oh nvm I found the correct file path!

**Comment by jukent** [comment]
I met points 2 and 3, will take a look at references.

**Pull request merged**
